/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hitesh' at '5/8/17 4:12 AM' with Gradle 2.9
 *
 * @author hitesh, @date 5/8/17 4:12 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
